services:
  app:
    image: ghcr.io/legincy/hsbo-sq-demo:latest
    container_name: hsbo-sq-demo-api
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${SERVER_PORT}:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  db:
    image: postgres:14-alpine
    container_name: hsbo-sq-demo-db
    env_file:
      - .env.docker
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
