services:
  db:
    image: postgres:14-alpine
    container_name: hsbo-sq-demo-db-dev
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  influxdb:
    image: influxdb:latest
    container_name: hsbo-sq-demo-influx
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx/data:/var/lib/influxdb2
      - ./data/influx/config:/etc/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: hsbo-sq-demo-grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
    - influxdb